### ISSUE TITLE
ents.GetAll/player.GetAll issue

### ISSUE THREAD

**Issue by Astralcircle** [Pika-Software/glua-patches#5]
You are returning the table itself, not a copy of it. This means that if you modify the output of ents.GetAll/player.GetAll, it will affect subsequent calls.
![image](https://github.com/user-attachments/assets/25967f0d-e8f7-4274-b264-86413d92703d)

**Comment by unknown-gd** [comment]
https://github.com/Pika-Software/glua-patches/commit/92a3fcd8385de25dc6c61fb9204b5224c6f30dca

**Comment by Astralcircle** [comment]
![image](https://github.com/user-attachments/assets/385b6ff8-5e43-4fa1-996d-b0ea125789d0)
Thanks for fast response
