### ISSUE TITLE
Incorrect behavior of is* functions

### ISSUE THREAD

**Issue by Astralcircle** [Pika-Software/glua-patches#7]
Tested only on isstring but should work on other functions too.
Example:
```lua
local fake_string = setmetatable({}, {__metatable = getmetatable("")})
print(isstring(fake_string)) --true, but should be false
```

**Comment by unknown-gd** [comment]
That's fine, setting such metatables is a developer issue, it makes no sense other than to intentionally break the game.

Speeding up `is*` checks in the current implementation is the only thing I've managed to implement that actually works fast and consistently. Developers should not use these metatables.

It is impossible to fix without significant performance loss.

**Comment by Astralcircle** [comment]
Just use debug.getmetatable?

**Comment by unknown-gd** [comment]
It is much slower than `getmetatable` and is labeled as depricated.

**Comment by Astralcircle** [comment]
Is that so? I just checked and debug.setmetatable was even faster than setmetatable. And about the deprecated mark, I don't think Rubat is going to destroy the debug library even more.
```lua
local SysTime = SysTime

local start_time = SysTime()

for i = 1, 10000 do
    local a = getmetatable("")
end

local end_time = SysTime()
print(end_time - start_time)

local start_time = SysTime()

for i = 1, 10000 do
    local a = debug.getmetatable("")
end

local end_time = SysTime()
print(end_time - start_time)
```
```
3.5800000205199e-05
1.2700000297627e-05
```

**Comment by unknown-gd** [comment]
> Just use debug.getmetatable?

https://github.com/Pika-Software/glua-patches/commit/db23df3a493f0f6a6bfb61335d47f4f36916d776
